"""empty message

Revision ID: cb7862e7e629
Revises: 747714f6c7ef
Create Date: 2025-09-15 22:39:04.961423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7862e7e629'
down_revision = '747714f6c7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(
        sa.Column('type_product', sa.String(length=50), nullable=False, server_default='type')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(
        sa.Column('type_product', sa.String(length=50), nullable=False, server_default='type')
    )

    # ### end Alembic commands ###
